### ISSUE TITLE
Add the rest of the CLBG scenarios?

### ISSUE THREAD

**Issue by danmoseley** [hanabi1224/Programming-Language-Benchmarks#204]
Hello, the maintainer of the [Computer Language Benchmark Game](https://benchmarksgame-team.pages.debian.net/benchmarksgame/) is not always able to update the numbers regularly -- he posted in their forum recently it may be a few months. Would you consider adding to this repo the benchmarks from there that you don't already have?

For example, I work on .NET, we shipped .NET 6 and I'm curious to see updated numbers for regex redux.

Also, it seems likely easier to offer submissions here, than over there.

**Comment by danmoseley** [comment]
If this is something you're interested in, perhaps I could offer some changes towards this.

**Comment by hanabi1224** [comment]
Sure I'm open to adding new problems, and you are more than welcome to contribute! 

Please note that programs are slightly modified before being imported. It uses file input instead of stdin (e.g. knucleotide). And output is made readable and smaller(e.g. mandelbrot) to avoid measuring overhead of unbuffered stdout

**Comment by hanabi1224** [comment]
FYI, I've added c# impl of regex-redux as well as some others in https://github.com/hanabi1224/Programming-Language-Benchmarks/pull/205

**Comment by danmoseley** [comment]
That's great. regex redux was the missing one I noticed. Curious to see how we fare.

Do you have thoughts about potentially including Preview versions of platforms? Eg in Feb we should have a .NET 7 preview 1. Amongst other things it will compile regexes at build time. It might be interesting to compare side by side.

**Comment by hanabi1224** [comment]
> including Preview versions of platforms

There is [bench_csharp_preview.yaml](https://github.com/hanabi1224/Programming-Language-Benchmarks/blob/main/bench/bench_csharp_preview.yaml) for dotnet 6 when it was in preview, I'd like to turn it back on for net 7 when the preview is out.
