### ISSUE TITLE
I have a new entry for one of the algorithms, can I publish a pull request please?

### ISSUE THREAD

**Issue by yonillasky** [hanabi1224/Programming-Language-Benchmarks#212]
Is there a way to ask individual contributors directly? how does it work? I'm fairly new to github.

I tried creating a local branch and pushing it to the repo; it says I don't have permission to do that.

**Comment by hanabi1224** [comment]
Plz refer to https://docs.github.com/en/get-started/quickstart/fork-a-repo

**Comment by yonillasky** [comment]
Thanks!
https://github.com/hanabi1224/Programming-Language-Benchmarks/pull/213
