### ISSUE TITLE
regex-redux (and others) - Input file is not in repository

### ISSUE THREAD

**Issue by carlosmspk** [hanabi1224/Programming-Language-Benchmarks#299]
For some reason, the input file was added to gitignore at `bench/algorithm/regex-redux`. Not quite sure what the purpose of that decision was, but the benchmark is unexecutable without it. I would request to have that gitignore file removed/edited and the input file included in the repository.

EDIT: noticed afterwards, that other benchmarks also make use of similarly named files, so regex-redux is not the only benchmark affected by this (`knucleotide` seems to also require such absent files).

**Comment by cyrusmsk** [comment]
In knucleotide at least we fave in.zip with input files.
I think they are living on server - just to reduce the size of the repo were gitignored

**Comment by carlosmspk** [comment]
Is it possible to have the link to these files? Or are they not public?

**Comment by carlosmspk** [comment]
Nevermind, I misread your response, I can see the zip file you referred to is at `bench/algorithm/knucleotide/in.zip`
My bad... Thanks for the response!
