### ISSUE TITLE
Is Xdebug enabled in PHP instance of benchmarks? 

### ISSUE THREAD

**Issue by cycle20** [hanabi1224/Programming-Language-Benchmarks#353]
Hi,

Is Xdebug enabled in PHP instance of benchmarks?
If yes, can you disable it? It causes a huge performance degradation to the engine.
(I saw some clues in the action log: Xdebug print outs are red flags to me)

Thank you,
Csongor

**Comment by hanabi1224** [comment]
Fixed. Thanks for reporting

**Comment by cycle20** [comment]
Thank you.
