### ISSUE TITLE
Maybe dismiss http-server problem?

### ISSUE THREAD

**Issue by cyrusmsk** [hanabi1224/Programming-Language-Benchmarks#370]
Web-servers are usually created in separate packages. It is not really related to language details, but to amount of time and effort that were put into development and optimization activities.
There are different benchmarks for  web-servers performance testing.
Current problem looks pretty strange.

**Comment by hanabi1224** [comment]
Ppl could always dismiss a problem when they find it not helpful.  If you're suggesting unpublish it, I would expect a stronger justification, like how it is wrong or misleading
