### ISSUE TITLE
Is the time on the website for the D (Dlang) HTTP server a mistake?

### ISSUE THREAD

**Issue by alecgargett** [hanabi1224/Programming-Language-Benchmarks#443]
Thanks to all the contributors for your work on this.

The time for the D http server on the website is 3.4 ms, about 30-50 times quicker than the second and third fastest implementations in Go and Rust, and 300 times quicker than the second fastest Dlang implementation. 3.4 ms is also smaller than its own standard deviation.

Perhaps even stranger, there doesn't seem to be any reference to http-server content in the D section of website/content on this repo:

https://github.com/hanabi1224/Programming-Language-Benchmarks/tree/f2172e6743dc97bf9e53a396b2ac4d33ee53683e/website/content/d

I also couldn't find where the times are stored to check if it was just a typo, or if was the real output of the (perhaps broken) test.

**Comment by alecgargett** [comment]
Looks like this has now been fixed. Thanks again for your work. Go is now a slight outlier, but not by as much as D was. I wonder if you're running multiple times and taking a mean or min? Given the D outlier previously, I wonder if there might be some issues with code actually running *quicker* when if fails, in which case taking a median of multiple runs (even just 3) could help.

**Comment by hanabi1224** [comment]
> The time for the D http server on the website is 3.4 ms

Yes, that indicates test failure. `D` `http-server` program is unstable, I might consider disable it.

> in which case taking a median of multiple runs (even just 3) could help.

It is currently the mean of N runs, and you can find stddev(standard deviation) column on the site.

**Comment by alecgargett** [comment]
Got it, thanks, a mean makes sense too.
