### ISSUE TITLE
Any chance of including the amount of time it took to compile the program, and not just the amount of time it took to run it?

### ISSUE THREAD

**Issue by alecgargett** [hanabi1224/Programming-Language-Benchmarks#445]
Any chance of including the amount of time it took to compile the program, and not just the amount of time it took to run it?

**Comment by hanabi1224** [comment]
The site won't include the amount of time it took to compile the program due to

- the setup is optimized for compile time
- different langs are compiled in parallel on CI which may run on different CPU models

**Comment by alecgargett** [comment]
Ok thanks

**Comment by igouy** [comment]
@alecgargett 

fwiw something like that has, for a long time, been shown in the program logs on the benchmarks game.

That data is now also shown on the comparison pages and [summarized](https://benchmarksgame-team.pages.debian.net/benchmarksgame/how-programs-are-measured.html#make-time).
