### ISSUE TITLE
What's the purpose?

### ISSUE THREAD

**Issue by besi1z** [hanabi1224/Programming-Language-Benchmarks#91]

**Comment by hanabi1224** [comment]
This is mainly to benchmark 2 things, performance between different programming languages and performance between different compilers or runtimes of the same language

**Comment by igouy** [comment]
And, as far as I can tell — measurements for some programming language implementations that not shown on the benchmarks game.

It's long seemed to me that "Of course, measurements of the ["proggit popular" language implementations like PyPy and LuaJIT are very likely to attract attention](https://www.reddit.com/r/programming/comments/1kxt7w/parallel_roguelike_levgen_benchmarks_rust_go_d/cbvnhcm/) and be the basis of another successful website (unlike more Fortran or Ada or Pascal or Lisp)."
