### ISSUE TITLE
Running on CI machines give inherently unstable results

### ISSUE THREAD

**Issue by eregon** [hanabi1224/Programming-Language-Benchmarks#98]
The benchmarks seem to be run in GitHub Actions on GitHub hosted runners.

Those runners are hosted in the cloud, they are probably shared machines running multiple workloads at the same time, etc.
So the results will likely be very noisy.

Is there a plan to address that?

Until then I think it would be useful to run each measurement a few times, or reuse the previous runs to compute the standard deviation or some other estimator of the variance, as this a big caveat.

**Comment by hanabi1224** [comment]
> I think it would be useful to run each measurement a few times

Currently, it runs each benchmark tasks multiple times and then calculates the average,  we can increase the number of runs and eliminate biased data in the future.

> So the results will likely be very noisy.

That was my worry too, and that's why I used multiple runs at the very beginning. But so far I found the results pretty stable with the tens of runs I've scheduled. (Which you can fork and test yourself)

**Comment by eregon** [comment]
Right, comparing on the same run and therefore same machine is already something.

I think the main thing missing then is stddev or so on the website.
I don't see any estimator of variance on e,g, https://programming-language-benchmarks.vercel.app/ruby currently.

**Comment by hanabi1224** [comment]
@eregon  Just updated site with std dev column, each task runs 3 times currently.

**Comment by eregon** [comment]
Thank you, that is useful.

One issue though is that it seems different languages are run in different CI jobs, looking at
https://github.com/hanabi1224/Programming-Language-Benchmarks/runs/2343185468?check_suite_focus=true

That means comparing between languages might be very misleading.
For instance, we found in ruby/setup-ruby that some GH hosted Ubuntu runners actually have different CPU models.

A way to address that would be to run all benchmarks in the same job, but I'm not sure if that's practical.
If not, I think a big warning about this would be warranted.

**Comment by hanabi1224** [comment]
> we found in ruby/setup-ruby that some GH hosted Ubuntu runners actually have different CPU models.

Does that happen on the same or different ubuntu version?  I have not noticed differences when I'm using the same ubuntu version (2004) here, but I believe ruby/setup-ruby run on different versions tho.

To mitigate this, I plan to gather and publish hardware information as well.  (I guess only cpu / mem are needed)

**Comment by eregon** [comment]
Also on the same ubuntu version: https://github.com/ruby/setup-ruby/issues/141#issuecomment-759117216

**Comment by hanabi1224** [comment]
All benchmark programs run in the same CI VM now
